# Generated by Django 3.0.1 on 2019-12-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_auto_20191205_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleddish',
            name='max_orders',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
