image: node:13.8.0-buster

cache:
  paths:
    - frontend/node_modules/
    - frontend/.yarn-cache/

before_script:
  - yarn --cwd frontend install --pure-lockfile --cache-folder .yarn-cache

test:
  stage: test
  script:
    - yarn --cwd frontend test --runInBand

source maps:
  stage: deploy
  script:
    - cd frontend
    - yarn build
    - ./upload_source_maps.sh
  only:
    - production

docker images:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose build
    - docker-compose push
  only:
    - production
