test:
  stage: test
  image: node:13.8.0-buster
  before_script:
    - yarn --cwd frontend install --pure-lockfile --cache-folder .yarn-cache
  script:
    - yarn --cwd frontend test --runInBand
  cache:
    paths:
      - frontend/node_modules/
      - frontend/.yarn-cache/

source maps:
  stage: deploy
  image: node:13.8.0-buster
  before_script:
    - yarn --cwd frontend install --pure-lockfile --cache-folder .yarn-cache
  script:
    - cd frontend
    - yarn build
    - ./upload_source_maps.sh
  cache:
    paths:
      - frontend/node_modules/
      - frontend/.yarn-cache/
  only:
    - production

docker images:
  stage: deploy
  image: docker
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - apk add --no-cache docker-compose
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose -f docker-compose.ci.yml build
    - docker-compose -f docker-compose.ci.yml push
  only:
    - production
