image: node:12.15.0-alpine3.11

cache:
  paths:
    - node_modules/
    - .yarn/

before_script:
  - yarn install

test:
  stage: test
  script:
    - yarn test --runInBand

pages:
  stage: deploy
  script:
    - yarn build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - production
