image: node:13.8.0-alpine3.11

cache:
  paths:
    - frontend/node_modules/
    - frontend/.yarn-cache/

before_script:
  - cd frontend
  - yarn install --pure-lockfile --cache-folder .yarn-cache

test:
  stage: test
  script:
    - cd frontend
    - yarn test --runInBand

pages:
  stage: deploy
  script:
    - cd frontend
    - yarn build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - production
