image: node:13.8.0-alpine3.11

cache:
  paths:
    - frontend/node_modules/
    - frontend/.yarn-cache/

before_script:
  - yarn --cwd frontend install --pure-lockfile --cache-folder .yarn-cache

test:
  stage: test
  script:
    - yarn --cwd frontend test --runInBand

source maps:
  stage: deploy
  script:
    - cd frontend
    - yarn build
    - ./upload_source_maps.sh
  only:
    - production
