image: node:12.15.0-alpine3.11

cache:
  paths:
    - frontend/node_modules/
    - frontend/.yarn/

before_script:
  - yarn --cwd frontend install

test:
  stage: test
  script:
    - yarn --cwd frontend test --runInBand

pages:
  stage: deploy
  script:
    - yarn --cwd frontend build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - production
