version: '3.6'

services:
  db:
    image: postgres:12.0-alpine
    env_file: .db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

  backend:
    build: .
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - backend_staticfiles:/app/staticfiles
      - backend_mediafiles:/app/mediafiles
    env_file: .env
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    volumes:
      - frontend_build:/app/build

  nginx:
    build: ./nginx
    volumes:
      - backend_staticfiles:/staticfiles:ro
      - backend_mediafiles:/mediafiles:ro
      - frontend_build:/usr/share/nginx/html:ro
    ports:
      - 1337:80
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
  backend_staticfiles:
  backend_mediafiles:
  frontend_build:
