version: '3.6'

services:
  backend:
    build:
      context: ./backend
      args:
        TIME_ZONE: $TIME_ZONE
    command: gunicorn samuel.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - backend_staticfiles:/app/staticfiles
      - backend_mediafiles:/app/mediafiles
    env_file: .env
    restart: always

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - backend_staticfiles:/staticfiles:ro
      - backend_mediafiles:/mediafiles:ro
    ports:
      - 1337:80
    depends_on:
      - backend
    restart: always

volumes:
  backend_staticfiles:
  backend_mediafiles:
