version: '3.6'

services:
  backend:
    image: registry.gitlab.com/samuel-bistro/samuel-bistro.gitlab.io/backend
    build:
      context: ./backend

  nginx:
    image: registry.gitlab.com/samuel-bistro/samuel-bistro.gitlab.io/nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
