version: '3.6'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: samuel_dev

  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      ENV: DEV
      DEBUG: 'on'
      SECRET_KEY: ad@i+gons+sq8dx_*i#a8zgy8@h(lg2c92y)2c*v77+=hrvy1q
      ALLOWED_HOSTS: pluto,10.0.0.11
      DATABASE_URL: psql://postgres:postgres@db:5432/samuel_dev
    depends_on:
      - db

volumes:
  postgres_dev_data:
