version: "3.6"

services:
  backend:
    image: eyalch/samuel-backend
    build: ./backend
    volumes:
      - backend_staticfiles:/app/staticfiles
      - backend_mediafiles:/app/mediafiles
    env_file: .env
    restart: always

  frontend:
    image: eyalch/samuel-frontend
    build: ./frontend
    volumes:
      - backend_staticfiles:/staticfiles:ro
      - backend_mediafiles:/mediafiles:ro
    ports:
      - 1337:80
    env_file: .env
    depends_on:
      - backend
    restart: always

volumes:
  backend_staticfiles:
  backend_mediafiles:
