version: '3.6'

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - /app/.venv/ # Don't copy the .venv directory
    network_mode: host
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      ENV: DEV
      DEBUG: 'on'
      SECRET_KEY: ad@i+gons+sq8dx_*i#a8zgy8@h(lg2c92y)2c*v77+=hrvy1q
      ALLOWED_HOSTS: pluto,10.0.0.11
      DATABASE_URL: psql://postgres:postgres@db:5432/samuel_dev
