version: '3.6'

services:
  backend:
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - /app/.venv/ # Don't copy the .venv directory
    ports:
      - 8000:8000
    env_file: .env
    environment:
      PYTHONDONTWRITEBYTECODE: 1
