version: '3.6'

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - /app/.venv/ # Don't copy the .venv directory
    network_mode: host
    env_file: .env
    environment:
      PYTHONDONTWRITEBYTECODE: 1
