version: '3.6'

services:
  backend:
    build: ./backend
    command: gunicorn samuel.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - backend_staticfiles:/app/staticfiles
      - backend_mediafiles:/app/mediafiles
    env_file: .env
    restart: always

  frontend:
    build: ./frontend
    volumes:
      - frontend_build:/app/build

  nginx:
    build: ./nginx
    volumes:
      - backend_staticfiles:/staticfiles:ro
      - backend_mediafiles:/mediafiles:ro
      - frontend_build:/usr/share/nginx/html:ro
    ports:
      - 1337:80
    depends_on:
      - backend
    restart: always

volumes:
  backend_staticfiles:
  backend_mediafiles:
  frontend_build:
