version: '3.6'

services:
  backend:
    image: docker.pkg.github.com/eyalch/samuel/backend
    build:
      context: ./backend

  nginx:
    image: docker.pkg.github.com/eyalch/samuel/nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
