version: "3.6"

services:
  tests:
    build:
      context: .
      target: base
    command: >
      bash -c "
        while !</dev/tcp/test_db/5432; do sleep 1; done &&
        ./manage.py test
      "
    env_file: ../.env.example
    environment:
      SECRET_KEY: secret-key
      DATABASE_URL: psql://postgres:password@test_db:5432/samuel_test
    depends_on:
      - test_db

  test_db:
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=samuel_test
