# Generated by Django 2.2.6 on 2019-10-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('dishes', '0001_initial'), ('dishes', '0002_auto_20191003_1608'), ('dishes', '0003_auto_20191003_1622')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default='', upload_to='dishes/')),
                ('next_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'dishes',
            },
        ),
    ]
