# Generated by Django 2.2.6 on 2019-10-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_squashed_0003_auto_20191003_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, upload_to='dishes/'),
        ),
    ]
