from . import env

CORONA_EMAIL_HOST_USER = env.str("CORONA_EMAIL_USER")
CORONA_EMAIL_HOST_PASSWORD = env.str("CORONA_EMAIL_PASSWORD")
CORONA_FROM_EMAIL = env.str("CORONA_EMAIL_USER")
CORONA_EMAIL_RECIPIENTS = env.list("CORONA_EMAIL_RECIPIENTS", default=[])
