# Generated by Django 3.0.2 on 2020-01-20 00:21

import django.contrib.auth.validators
from django.db import migrations, models


def email_to_username(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        user.username = user.email[:user.email.index('@')]
        user.save(update_fields=['username'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191019_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.RunPython(email_to_username),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
