# Generated by Django 3.0.3 on 2020-03-02 23:12

from django.db import migrations, models
from django_auth_ldap.backend import LDAPBackend


def update_users(apps, schema_editor):
    """
    Re-populate the users to set the `domain` field
    """
    User = apps.get_model("users", "User")
    backend = LDAPBackend()
    for user in User.objects.all():
        backend.populate_user(user.username)


class Migration(migrations.Migration):

    dependencies = [("users", "0003_auto_20200120_0021")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="domain",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.RunPython(update_users),
    ]
