name: Main

on:
  push:
    branches: [master, production]

jobs:
  test-frontend:
    name: Test frontend
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2.1.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 13.8.0

      - run: yarn install --pure-lockfile
      - run: yarn test --runInBand

  test-backend:
    name: Test backend
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2.1.0

      - run: docker-compose -f docker-compose.test.yml up --exit-code-from tests

  build-and-push:
    name: Build and push Docker images
    runs-on: ubuntu-18.04
    if: github.ref == 'refs/heads/production'
    needs: [test-frontend, test-backend]
    steps:
      - uses: actions/checkout@v2.1.0

      - name: Rename .env.example to .env
        run: mv .env.example .env

      - name: Build images
        run: docker-compose build
          --build-arg VERSION=${{ github.sha }}
          --build-arg BRANCH=${{ github.ref }}

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin

      - name: Push images
        run: docker-compose push
